import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CategoryProvider from "./_context/CategoryContext";
import FoodProvider from "./_context/FoodContext";
import UserProvider from "./_context/UserContext";
import OrderProvider from "./_context/OrderContext";
import CartProvider from "./_context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
           <OrderProvider>
          <CategoryProvider>
            <FoodProvider>
              <UserProvider>{children}</UserProvider>
            </FoodProvider>
          </CategoryProvider>
        </OrderProvider>
        </CartProvider>
       
      </body>
    </html>
  );
}
